// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrivateTutoringApplication.Model.Infrastructure;

namespace PrivateTutoringApplication.Model.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200223194642_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PrivateTutoringApplication.Model.Entity.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("CinsiyetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<DateTime>("EklenmeZamani")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("EkleyenId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("KimlikNo")
                        .HasColumnType("character varying(31)")
                        .HasMaxLength(31);

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("character varying(127)")
                        .HasMaxLength(127);

                    b.Property<string>("Resim")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Sifre")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<Guid?>("SifreGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SifreGuidGecerlilik")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.Property<string>("Soyad")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<string>("TuzlamaDegeri")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<int?>("YetkiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EkleyenId");

                    b.HasIndex("YetkiId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("PrivateTutoringApplication.Model.Entity.Yetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("character varying(127)")
                        .HasMaxLength(127);

                    b.Property<string>("Adi")
                        .HasColumnType("character varying(63)")
                        .HasMaxLength(63);

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EklenmeZamani")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Goster")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<bool>("Silindi")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Yetki");
                });

            modelBuilder.Entity("PrivateTutoringApplication.Model.Entity.Kullanici", b =>
                {
                    b.HasOne("PrivateTutoringApplication.Model.Entity.Kullanici", "Ekleyen")
                        .WithMany()
                        .HasForeignKey("EkleyenId");

                    b.HasOne("PrivateTutoringApplication.Model.Entity.Yetki", "Yetki")
                        .WithMany()
                        .HasForeignKey("YetkiId");
                });
#pragma warning restore 612, 618
        }
    }
}
